### ISSUE TITLE
unable to do it can u make the instructions a bit more elaborate 

### ISSUE THREAD

**Issue by Rajulrajramesan** [haexhub/huaweiBootloaderHack#2]
unable to run the program i need the detailed instruction guide
where to place these files
all the required files
the exact procedure
i need to unlock my nova3i ine-lx1r

**Comment by haexhub** [comment]
Hi,
in step 4 is everything you need to do. Just clone the repo, cd into and run python unlock <IMEI of your phone>
Can you describe your problem more detailed?

**Comment by Rajulrajramesan** [comment]
> Hi,
> in step 4 is everything you need to do. Just clone the repo, cd into and run python unlock
> Can you describe your problem more detailed?

i dont know how to do it can u give me in detail how to do it step by step or some video as reference that is the problem

**Comment by Rajulrajramesan** [comment]
what and how am i supposed to do

**Comment by Rajulrajramesan** [comment]
when ever i try to open it ,it just opens fast then loads and closes itself

**Comment by Rajulrajramesan** [comment]
after fixing the previous error now i get this error
image link for the error below
![error](https://user-images.githubusercontent.com/67539947/86342046-b1985480-bc74-11ea-96f9-49a693f00928.jpg)

**Comment by haexhub** [comment]
can you please try again? I fixed the initial json file
