### ISSUE TITLE
"* shot 1 with code 1000000000000000 *", is this the normal response?

### ISSUE THREAD

**Issue by AFlyingBird90** [haexhub/huaweiBootloaderHack#3]
Hi, after the phone is in fastboot mode, is this the normal response? Sorry if I used the incorrect terminology, not a program developer myself. Thank you for your time!
![Screen Shot 2020-07-26 at 8 43 41 AM](https://user-images.githubusercontent.com/22230037/88479340-63493f00-cf1c-11ea-9239-8f172cd24634.png)

**Comment by AFlyingBird90** [comment]
It stayed there for a night. 
My device is a Huawei nova youth (P10 Lite for Europe). 
I think it doesn't work on my phone.

**Comment by haexhub** [comment]
Thats strange. * shot 1 with code ############### * is normal and shows the current state of the hack. But it should increase much faster. Did you tried it again with same result?
I use this script for my P20 and its working.
