### ISSUE TITLE
Not saving failedAttemps.json file

### ISSUE THREAD

**Issue by salimcansatici** [haexhub/huaweiBootloaderHack#7]
Hi,

* shot 1 with code 1000000000000000 *

but when I check it does not write the tried code to the json file.

Thanks

**Comment by salimcansatici** [comment]
The problem is solved :) Will he try again when we close or interrupt? Or will it skip the codes it tried?

**Comment by haexhub** [comment]
Hi,
the failed attempts will be saved in the json file, so the program can skip it, if you interrupted or stoped the program.

**Comment by salimcansatici** [comment]
Thanks :)
